name: Create Release

on:
  workflow_run:
    workflows: ["Java Tests"]
    types:
      - completed
    branches: [main]

permissions:
  contents: write

jobs:
  create-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Prepare Build Directories
        run: |
          mkdir -p temp/student temp/solution

          # Sync student directory
          rsync -av --delete \
            --exclude 'test/build/' \
            --exclude 'test/solution/' \
            --exclude 'base/' \
            src/ temp/student/

          # Sync solution directory
          rsync -av --delete \
            --exclude 'test/build/' \
            --exclude 'test/validate/' \
            src/ temp/solution/

      - name: Get Latest Tag
        id: latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Check for Changes in student directory
        id: student_changes
        run: |
          git diff --exit-code -- temp/student || echo "Changes detected in student directory"

      - name: Check for Changes in solution directory
        id: solution_changes
        run: |
          git diff --exit-code -- temp/solution || echo "Changes detected in solution directory"

      - name: Skip Release if No Changes
        if: ${{ steps.student_changes.outcome == 'success' && steps.solution_changes.outcome == 'success' }}
        run: echo "No changes detected in student or solution directories, skipping release creation."

      - name: Create Zip Archives
        if: ${{ steps.student_changes.outcome != 'success' || steps.solution_changes.outcome != 'success' }}
        run: |
          zip -r student.zip temp/student
          zip -r solution.zip temp/solution

      - name: Create GitHub Release
        if: ${{ steps.student_changes.outcome != 'success' || steps.solution_changes.outcome != 'success' }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            student.zip
            solution.zip
          tag_name: v${{ github.run_number }}
          name: Build V${{ github.run_number }}
          body: |
            This release contains the following build directories:
            - **student**
            - **solution**
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup Temporary Files
        run: rm -rf temp student.zip solution.zip
