name: Create Release

on:
  workflow_run:
    workflows: ["Java Tests"]
    types:
      - completed
    branches: [main]

permissions:
  contents: write

jobs:
  create-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Prepare Build Directories
        run: |
          mkdir -p temp/student temp/solution

          # Sync student directory
          rsync -av --delete \
            --exclude 'test/build/' \
            --exclude 'test/solution/' \
            --exclude 'base/' \
            src/ temp/student/

          # Sync solution directory
          rsync -av --delete \
            --exclude 'test/build/' \
            --exclude 'test/validate/' \
            src/ temp/solution/

      - name: Check for Changes in Student Directory
        id: check_student_changes
        run: |
          git diff --exit-code --quiet temp/student || echo "Changes detected in student directory" > student_changes.txt
          if [ -f student_changes.txt ]; then
            echo "Student directory has changes."
            echo "STUDENT_CHANGED=true" >> $GITHUB_ENV
          else
            echo "No changes in student directory."
            echo "STUDENT_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Check for Changes in Solution Directory
        id: check_solution_changes
        run: |
          git diff --exit-code --quiet temp/solution || echo "Changes detected in solution directory" > solution_changes.txt
          if [ -f solution_changes.txt ]; then
            echo "Solution directory has changes."
            echo "SOLUTION_CHANGED=true" >> $GITHUB_ENV
          else
            echo "No changes in solution directory."
            echo "SOLUTION_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Exit if No Changes Detected
        run: |
          if [ "$STUDENT_CHANGED" == "false" ] && [ "$SOLUTION_CHANGED" == "false" ]; then
            echo "No changes detected in both directories, exiting workflow."
            exit 0
          fi

      - name: Create Zip Archives
        if: ${{ env.STUDENT_CHANGED == 'true' || env.SOLUTION_CHANGED == 'true' }}
        run: |
          if [ "$STUDENT_CHANGED" == "true" ]; then
            zip -r student.zip temp/student
          fi
          if [ "$SOLUTION_CHANGED" == "true" ]; then
            zip -r solution.zip temp/solution
          fi

      - name: Create GitHub Release
        if: ${{ env.STUDENT_CHANGED == 'true' || env.SOLUTION_CHANGED == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            student.zip
            solution.zip
          tag_name: v${{ github.run_number }}
          name: Build V${{ github.run_number }}
          body: |
            This release contains the following build directories:
            - **student** (if changes detected)
            - **solution** (if changes detected)
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup Temporary Files
        run: rm -rf temp student.zip solution.zip
