name: Java Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'recursive'
          persist-credentials: false
          lfs: true

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create lib directory
        run: mkdir -p lib

      - name: Download JUnit Dependencies
        run: |
          wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.2/junit-platform-console-standalone-1.9.2.jar -P lib/

      - name: Compile
        run: |
          javac -cp "lib/*:src" -d out/production/Torrent $(find src -name "*.java")

      - name: Run Tests
        run: |
          java -jar lib/junit-platform-console-standalone-1.9.2.jar \
            --class-path out/production/Torrent \
            --scan-class-path \
            --include-classname ".*Test" \
            --reports-dir=test-results

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.20.0/allure-2.20.0.tgz -O allure.tgz
          tar -xzf allure.tgz
          sudo mv allure-2.20.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate HTML Report
        run: |
          allure generate test-results -o test-results-html

      - name: Upload Test Results (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-html
          path: test-results-html/
