name: Java Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'recursive'
          persist-credentials: false
          lfs: true

      - name: GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Create lib directory
        run: mkdir -p lib

      - name: Download JUnit Dependencies
        run: |
          wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.2/junit-platform-console-standalone-1.9.2.jar -P lib/

      - name: Compile
        run: |
          javac -cp "lib/*:src" -d out/production/Torrent $(find src -name "*.java")

      - name: Run Tests
        run: |
          java -jar lib/junit-platform-console-standalone-1.9.2.jar \
            --class-path out/production/Torrent \
            --scan-class-path \
            --include-classname ".*Test" \
            --reports-dir=test-results
          
      - name: Run Main
        run: |
          java -cp out/production/Torrent simulation.Simulation
        continue-on-error: false

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/